# Azure Pipeline YAML file

name: 1.0.0$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    include:
    - '*'

pr:
  drafts: false

variables:
  _IS_BUILD_CANARY: false
  _RELEASE_NAME: 7thHeavenCatalogs
  _RELEASE_VERSION: v0
  _BUILD_VERSION: $(Build.BuildNumber)
  _BUILD_BRANCH: $(Build.SourceBranch)

pool:
  vmImage: 'windows-2022'

steps:
- checkout: self
- task: PowerShell@2
  displayName: 'Prepare $(_RELEASE_NAME) Env'
  inputs:
    filePath: $(Build.Repository.LocalPath)\.ci\prepare.ps1
- task: GitHubRelease@0
  condition: and(eq(variables._IS_BUILD_CANARY, 'true'), not(contains(variables._BUILD_BRANCH, 'refs/pull/')), succeeded())
  displayName: 'Delete $(_RELEASE_NAME) Release (Canary)'
  continueOnError: true
  inputs:
    gitHubConnection: github_ci
    action: delete
    tagSource: manual
    tag: canary
- task: GitHubRelease@0
  condition: and(eq(variables._IS_BUILD_CANARY, 'true'), not(contains(variables._BUILD_BRANCH, 'refs/pull/')), succeeded())
  displayName: 'Create $(_RELEASE_NAME) Release (Canary)'
  inputs:
    gitHubConnection: github_ci
    assets: $(Build.Repository.LocalPath)\catalogs\*.xml
    isPreRelease: true
    tagSource: manual
    tag: canary
    title: $(_RELEASE_NAME)-$(_RELEASE_VERSION)
    releaseNotesSource: input
    releaseNotes: |
      This is a canary build. Please be aware it may be prone to crashing and is NOT tested by anyone. Use this build AT YOUR OWN RISK!
- task: GitHubRelease@0
  condition: and(eq(variables._IS_BUILD_CANARY, 'false'), not(contains(variables._BUILD_BRANCH, 'refs/pull/')), succeeded())
  displayName: 'Create $(_RELEASE_NAME) Release (Stable)'
  inputs:
    gitHubConnection: github_ci
    assets: $(Build.Repository.LocalPath)\catalogs\*.xml
    title: $(_RELEASE_NAME)-$(_RELEASE_VERSION)
