name: 7th-Heaven-Catalogs

run-name: 1.0.0.${{ github.run_number }}

on:
  push:
    branches:
    - master
    tags:
    - "*"
  pull_request:
    branches:
    - master

env:
  _IS_BUILD_CANARY: false
  _IS_GITHUB_RELEASE: false
  _RELEASE_NAME: 7thHeavenCatalogs
  _RELEASE_VERSION: v0
  _BUILD_BRANCH: "${{ github.ref }}"
  _BUILD_VERSION: "1.0.0.${{ github.run_number }}"
  # GIT: Fix reporting from stderr to stdout
  GIT_REDIRECT_STDERR: 2>&1

jobs:
  CICD:
    runs-on: windows-latest
    timeout-minutes: 1440
    strategy:
      max-parallel: 1
    steps:
    - name: Set Git Config
      run: |
        git config --global core.autocrlf false
        git config --global core.filemode false
        git config --global core.longpaths true
    - name: Checkout
      uses: actions/checkout@v4.1.0
    - name: Prepare Env
      run: ".github/workflows/prepare.ps1"
      shell: pwsh
    - name: Publish Canary release
      uses: ncipollo/release-action@v1
      if: env._IS_GITHUB_RELEASE == 'true' && env._IS_BUILD_CANARY == 'true' && success()
      with:
        artifacts: "${{ github.workspace }}/catalogs/*.xml"
        allowUpdates: true
        generateReleaseNotes: true
        prerelease: true
        removeArtifacts: true
        tag: canary
        name: "${{ env._RELEASE_NAME }}-${{ env._RELEASE_VERSION }}"
        body: |
          This is a canary build. Please be aware it may be prone to crashing and is NOT tested by anyone. Use this build AT YOUR OWN RISK!
    - name: Publish Stable release
      uses: ncipollo/release-action@v1
      if: env._IS_GITHUB_RELEASE == 'true' && env._IS_BUILD_CANARY == 'false' && success()
      with:
        artifacts: "${{ github.workspace }}/catalogs/*.xml"
        generateReleaseNotes: true
        makeLatest: true
        removeArtifacts: true
        name: "${{ env._RELEASE_NAME }}-${{ env._RELEASE_VERSION }}"
